DEVICE_PATH := device/xiaomi/myron

# Flashlight
OF_USE_GREEN_LED := 0
OF_FL_PATH1 := /sys/class/leds/yellow:flash-0

# Partition tools
OF_DYNAMIC_FULL_SIZE := 14495514624
OF_DISPLAY_FORMAT_FILESYSTEMS_DEBUG_INFO := 1
OF_FORCE_DATA_FORMAT_F2FS := 1
OF_WIPE_METADATA_AFTER_DATAFORMAT := 1
OF_WORKAROUND_BACKUP_BUG := 1

# Kernel
OF_FORCE_PREBUILT_KERNEL := 1

# Display
# Resolution: 1200x2608
OF_SCREEN_H := 2750
OF_STATUS_H := 141
OF_STATUS_INDENT_LEFT := 56
OF_STATUS_INDENT_RIGHT := 56
OF_HIDE_NOTCH := 1
OF_CLOCK_POS := 1
OF_ALLOW_DISABLE_NAVBAR := 0
OF_OPTIONS_LIST_NUM := 6
